"""Ordine narrativo usato dal comando di rendering."""

SCENES = [{'name': 'VecFieldWithSteam',
  'title': 'Campo vettoriale e rotore',
  'module': 'introduzione',
  'new': False},
 {'name': 'VecFieldWithSteamContinua',
  'title': 'Rotore visto in 3D',
  'module': 'introduzione',
  'new': False},
 {'name': 'Hypotesys',
  'title': 'Ipotesi di regolarità',
  'module': 'introduzione',
  'new': False},
 {'name': 'SumDotProducts',
  'title': 'Prodotto scalare lungo la curva',
  'module': 'green',
  'new': False},
 {'name': 'CirculationIntegral',
  'title': 'Dalla somma alla circuitazione',
  'module': 'completamento',
  'new': True},
 {'name': 'GreenAnalytic',
  'title': 'Dimostrazione sul quadrato',
  'module': 'green',
  'new': False},
 {'name': 'LocalLimit',
  'title': 'Limite sul quadrato piccolo',
  'module': 'completamento',
  'new': True},
 {'name': 'TwoSquares',
  'title': 'Cancellazione fra due quadrati',
  'module': 'green',
  'new': False},
 {'name': 'GreenGlobal',
  'title': 'Teorema di Green globale',
  'module': 'completamento',
  'new': True},
 {'name': 'StokesSurface',
  'title': 'Teorema di Stokes sulla superficie',
  'module': 'completamento',
  'new': True},
 {'name': 'FundamentalTheorem',
  'title': 'Teorema fondamentale del calcolo',
  'module': 'completamento',
  'new': True},
 {'name': 'GeneralizedStokes',
  'title': 'Teorema di Stokes generalizzato',
  'module': 'completamento',
  'new': True}]

EXPERIMENTS = ['VecFieldWithMass',
 'VecFieldWithSteam2',
 'GreenVisual',
 'Green_approx',
 'ParialApprox',
 'Finale']
